-- Insert 25 products (5 per category)
INSERT INTO products (category_id, name, slug, description, base_price, created_at) VALUES
(1, 'Áo Thun Basic Trắng', 'ao-thun-basic-trang', 'Áo thun cotton 100% thoáng mát, form regular phù hợp mọi lứa tuổi', 150000, NOW()),
(1, 'Áo Thun Polo Nam', 'ao-thun-polo-nam', 'Áo polo cao cấp, thiết kế thanh lịch cho phái mạnh', 250000, NOW()),
(1, 'Áo Thun Oversize Đen', 'ao-thun-oversize-den', 'Áo thun form rộng phong cách streetwear hiện đại', 180000, NOW()),
(1, 'Áo Thun Họa Tiết Vintage', 'ao-thun-hoa-tiet-vintage', 'Áo thun in họa tiết retro độc đáo, chất liệu mềm mại', 200000, NOW()),
(1, 'Áo Thun Thể Thao', 'ao-thun-the-thao', 'Áo thun thể thao thoáng khí, thấm hút mồ hôi tốt', 170000, NOW()),
(2, 'Quần Jean Skinny Xanh', 'quan-jean-skinny-xanh', 'Quần jean ôm body, chất denim cao cấp co giãn tốt', 450000, NOW()),
(2, 'Quần Jean Baggy Đen', 'quan-jean-baggy-den', 'Quần jean form rộng phong cách Hàn Quốc', 480000, NOW()),
(2, 'Quần Jean Rách Gối', 'quan-jean-rach-goi', 'Quần jean rách phong cách cá tính, năng động', 420000, NOW()),
(2, 'Quần Jean Ống Đứng', 'quan-jean-ong-dung', 'Quần jean ống đứng cổ điển, dễ phối đồ', 400000, NOW()),
(2, 'Quần Jean Wash Nhạt', 'quan-jean-wash-nhat', 'Quần jean wash màu nhạt phong cách vintage', 460000, NOW()),
(3, 'Giày Sneaker Trắng', 'giay-sneaker-trang', 'Giày sneaker basic màu trắng, dễ phối đồ', 550000, NOW()),
(3, 'Giày Thể Thao Running', 'giay-the-thao-running', 'Giày chạy bộ chuyên dụng, đế êm ái', 650000, NOW()),
(3, 'Dép Sandal Da', 'dep-sandal-da', 'Dép sandal da thật, thiết kế tối giản sang trọng', 380000, NOW()),
(3, 'Giày Boot Cổ Cao', 'giay-boot-co-cao', 'Giày boot da lộn phong cách mạnh mẽ', 850000, NOW()),
(3, 'Giày Lười Nam', 'giay-luoi-nam', 'Giày lười da công sở lịch sự', 480000, NOW()),
(4, 'Mũ Lưỡi Trai', 'mu-luoi-trai', 'Mũ cap thêu logo, chất liệu vải bền đẹp', 120000, NOW()),
(4, 'Thắt Lưng Da', 'that-lung-da', 'Thắt lưng da bò thật 100%, khóa kim loại cao cấp', 280000, NOW()),
(4, 'Kính Mát Gọng Tròn', 'kinh-mat-gong-tron', 'Kính mát thời trang, chống tia UV hiệu quả', 350000, NOW()),
(4, 'Ví Da Nam', 'vi-da-nam', 'Ví da bò thật, nhiều ngăn tiện dụng', 320000, NOW()),
(4, 'Đồng Hồ Thời Trang', 'dong-ho-thoi-trang', 'Đồng hồ nam thiết kế tối giản, dây da sang trọng', 680000, NOW()),
(5, 'Túi Tote Canvas', 'tui-tote-canvas', 'Túi vải canvas đựng đồ đa năng, phong cách tối giản', 180000, NOW()),
(5, 'Balo Laptop', 'balo-laptop', 'Balo đựng laptop 15 inch, nhiều ngăn tiện lợi', 450000, NOW()),
(5, 'Túi Đeo Chéo', 'tui-deo-cheo', 'Túi đeo chéo nhỏ gọn, phù hợp đi chơi', 220000, NOW()),
(5, 'Túi Xách Da Công Sở', 'tui-xach-da-cong-so', 'Túi xách da cao cấp cho doanh nhân', 850000, NOW()),
(5, 'Túi Du Lịch', 'tui-du-lich', 'Túi du lịch size lớn, chất liệu chống nước', 580000, NOW());
